# 2.3.1 Scalars

In [5]:
import torch

In [7]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x,y,x + y, x * y, x / y, x**y


(tensor(3.), tensor(2.), tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

# 2.3.2 Vectors

In [8]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [9]:
x[2]

tensor(2)

In [10]:
x[1]

tensor(1)

In [11]:
x[0]

tensor(0)

In [13]:
x[3] # index out of the bound for dimension 0 with size 3

IndexError: index 3 is out of bounds for dimension 0 with size 3

In [14]:
len(x)

3

In [15]:
x.shape

torch.Size([3])

# 2.3.3 Matrices

In [16]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [17]:
A.shape

torch.Size([3, 2])

In [19]:
A[0][0], A[0][1]

(tensor(0), tensor(1))

In [20]:
A[1][0], A[1][1]

(tensor(2), tensor(3))

In [21]:
A[2][0], A[2][1]

(tensor(4), tensor(5))

In [24]:
A[0:2][0:2]

tensor([[0, 1],
        [2, 3]])

In [26]:
A[0:2][0]

tensor([0, 1])

In [28]:
A[0:2][1]

tensor([2, 3])

In [30]:
A[0:3][2]

tensor([4, 5])

In [31]:
A, A.T

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 2, 4],
         [1, 3, 5]]))

In [36]:
A.shape, A.T.shape  # Transpose of a matrix 

(torch.Size([3, 3]), torch.Size([3, 3]))

In [34]:
 A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
 A == A.T  # Called Symmetric matrix 

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

# 2.3.4 Tensors

In [35]:
 torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

# 2.3.5 Basic Properties of Tensor Arithmetic

In [42]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone() # Assign a copy of A to B by allocating new memory
A, A + B  # element wise addtions 

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [43]:
# The elementwise product of two matrices is called their Hadamard product.
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [45]:
# Adding or multiplying a scalar and a tensor produces a result with the same shape as  the original tensor.
a = 2
X = torch.arange(24).reshape(2,3,4)
X, a + X, (a * X).shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

# 2.3.6 Reduction

In [46]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [47]:
A, A.shape, A.sum()

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor(15.))

In [52]:
A,  A.shape, A.sum(axis=0)    # 2 rows and 3 columns 

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([3., 5., 7.]))

In [53]:
A.sum(axis=0).shape

torch.Size([3])

In [54]:
 A, A.shape, A.sum(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([ 3., 12.]))

In [66]:
A.sum(axis=1).shape   # sum accross cokumns and row wise 

torch.Size([2])

In [50]:
A.shape

torch.Size([2, 3])

In [51]:
A.shape[0], A.shape[1]

(2, 3)

In [56]:
 A.sum(axis=[0, 1]) == A.sum() # Same as A.sum()

tensor(True)

In [58]:
A, A.sum(), A.sum(axis=0), A.sum(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(15.),
 tensor([3., 5., 7.]),
 tensor([ 3., 12.]))

In [59]:
 A.sum(axis=[0, 1])

tensor(15.)

In [60]:
 A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [61]:
 A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

# 2.3.7 Non-Reduction Sum

In [67]:
A = torch.arange(16, dtype=torch.float32).reshape(4, 4)

In [68]:
A, A.shape   # 2 rows and 3 columns 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]),
 torch.Size([4, 4]))

In [70]:
A.sum(axis=0) # sum accros rows (column wise) 

tensor([24., 28., 32., 36.])

In [71]:
sum_A = A.sum(axis=1, keepdims=True)  # axis = 1 sum accross columns (row wise)
sum_A, sum_A.shape # 4 rows , 1 columns 

(tensor([[ 6.],
         [22.],
         [38.],
         [54.]]),
 torch.Size([4, 1]))

In [72]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778]])

In [75]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [78]:
 A.cumsum(axis=0)  #cumulative sum row wise  top to dowan wards 

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.]])

In [79]:
A.cumsum(axis=1) # cumulative sum column wise left to write 

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.]])

# 2.3.8 Dot Products

In [95]:
y = torch.ones(3, dtype = torch.float32)
y, x

(tensor([1., 1., 1.]), tensor([0., 1., 2.]))

In [100]:
y.shape, x.shape

(torch.Size([3]), torch.Size([3]))

In [101]:
torch.dot(x, y)

tensor(3.)

In [102]:
x = x.T
x.shape, torch.dot(x, y)

(torch.Size([3]), tensor(3.))

In [103]:
y = y.T
y, torch.dot(x, y)

(tensor([1., 1., 1.]), tensor(3.))

### (column vector) × (row vector) → matrix (Outer product )


In [105]:
col = torch.tensor([[1],
                    [2],
                    [3]])     # shape (3, 1)

row = torch.tensor([[4, 5, 6]])  # shape (1, 3)


In [108]:
M = col @ row   # Outer product
print(M)


tensor([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]])


✔️ Key Points

A row vector in PyTorch: shape (1, n)

A column vector: shape (m, 1)

Their matrix product (m,1) @ (1,n) gives a matrix of shape (m,n)

# 2.3.9 Matrix–Vector Products

In [118]:
A.shape
x = torch.arange(4, dtype=torch.float32)
A , x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]),
 tensor([0., 1., 2., 3.]))

In [121]:
A.shape, x.shape

(torch.Size([4, 4]), torch.Size([4]))

In [119]:
torch.mv(A,x)  # 4 x 1

tensor([14., 38., 62., 86.])

In [122]:
A@x

tensor([14., 38., 62., 86.])

<img src="images/matXcol.png" width="3000">

In [123]:
A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])  # (2, 3)

x = torch.tensor([[1.],
                  [1.],
                  [1.]])          # (3, 1)

y = A @ x
print(y)


tensor([[ 6.],
        [15.]])


⚙️ 2. Matrix × Row Vector (NOT standard)

This is not a standard linear algebra operation unless you transpose the vector.

If you have a row vector:

In [128]:
v = torch.tensor([1., 1., 1.])   # shape (3,)
v.shape

torch.Size([3])

In [129]:
A @ v

tensor([ 6., 15.])

In [130]:
v_col = v.reshape(3, 1)
A @ v_col


tensor([[ 6.],
        [15.]])

| Operation     | Shapes        | Result |
| ------------- | ------------- | ------ |
| A @ x         | (m,n) × (n,1) | (m,1)  |
| xᵀ @ A        | (1,n) × (n,m) | (1,m)  |
| Outer product | (m,1) × (1,n) | (m,n)  |


# 2.3.11  Norms

In [131]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [134]:
 torch.abs(u)

tensor([3., 4.])

In [135]:
 torch.sum(u)

tensor(-1.)

In [133]:
 torch.abs(u).sum()

tensor(7.)

<img src="images/ForbeniusNorm.png" width="3000">

In [136]:
 torch.norm(torch.ones((4, 9)))

tensor(6.)