In [3]:
%matplotlib inline
import numpy as np
# import pandas as pd
# import seaborn as sns
import matplotlib as plt 
from matplotlib_inline import backend_inline

In [6]:
def f(x):
    return 3 * x ** 2- 4 * x
f(1)

-1

In [8]:
f(1) , f(2), f(5)

(-1, 4, 55)

In [9]:
10.0**np.arange(-1,-6,-1)

array([1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05])

In [10]:
for h in 10.0**np.arange(-1,-6,-1):
    print(f'h={h:.5f}, numerical limit={(f(1+h)-f(1))/h:.5f}')
 

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


In [11]:
 def use_svg_display(): #@save
     backend_inline.set_matplotlib_formats('svg')
 """Use the svg format to display a plot in Jupyter."""

'Use the svg format to display a plot in Jupyter.'

In [1]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

In [2]:
import torch

# 2.5 Automatic Differentiation

### 2.5.1 A Simple Function

In [18]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [19]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad # The gradient is None by default

In [20]:
y = 2 * torch.dot(x, x) # 2X^TX  # dot product and then multiplied by 2
y

tensor(28., grad_fn=<MulBackward0>)

In [21]:
 # Wecannowtake the gradient of y with respect to x by calling its backward method. Next,
 # we can access the gradient via x’s grad attribute.
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [23]:
x.grad == 4*x

tensor([True, True, True, True])

In [25]:
x.grad.zero_() # Reset the gradient
y = x.sum()
y.backward()
x.grad   

tensor([1., 1., 1., 1.])