In [1]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import torch

In [8]:
# Each of these values is called an element of the tensor. The tensor x contains 12 elements
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
x.numel() # to know the total number of elements present in the tensor

12

In [12]:
x.shape

torch.Size([12])

In [10]:
torch.Size([12])

torch.Size([12])

In [14]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
X.shape  # 3 rows and 4 columns 

torch.Size([3, 4])

In [21]:
x.reshape(-1,4) #by -1 we automatically infer one compopnent of the shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
x.reshape(3,-1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [26]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [27]:
torch.ones((2,3,4)).shape

torch.Size([2, 3, 4])

In [39]:
torch.randn(3,4)  # sampling from standard normal distribution

# Here, we construct a
#  matrix with a list of lists, where the outermost list corresponds to axis 0, and the inner list
#  corresponds to axis 1

tensor([[-0.6191,  0.4783, -0.6994,  1.1122],
        [ 0.3906,  0.9406, -0.2178,  1.3142],
        [-1.4612, -0.1000,  0.0517, -1.5349]])

In [41]:
torch.randn(3,4)[0]

tensor([-2.1108, -0.6198, -0.5303, -0.9273])

In [42]:
torch.randn(3,4)[1]

tensor([ 0.0226,  0.6903, -0.4466,  0.1953])

In [43]:
torch.randn(3,4)[2]

tensor([ 0.4681, -0.1059, -0.3515,  0.6225])

In [44]:
torch.randn(3,4)[3]

IndexError: index 3 is out of bounds for dimension 0 with size 3

In [49]:
torch.randn(3,4)[0][0]

tensor(0.1372)

In [48]:
torch.randn(3,4)[2][3]

tensor(-1.1933)

In [50]:
 torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [51]:
 torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])[0]

tensor([2, 1, 4, 3])

In [52]:
 torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])[0][0]

tensor(2)

In [54]:
 torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])[1]

tensor([1, 2, 3, 4])

In [55]:
 torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])[1][3] 

tensor(4)

# 2.1.2 Indexing and Slicing

### X[start:stop]

In [57]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [62]:
X[-1] # selects the last row   

tensor([ 8.,  9., 10., 11.])

In [63]:
X[1:3] # X[start:stop-1] i.e X[ print the 1 the row and 2nd row and row indexing start with 0]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [64]:
# Beyond reading them, we can also write elements of a matrix by specifying indices.
X[1,2]

tensor(6.)

In [67]:
X[1,2] = 777    # change the value at position 1st row and 3rd colum

In [68]:
X

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 777.,   7.],
        [  8.,   9.,  10.,  11.]])

In [69]:
X[:2, :2] = 99
X

tensor([[ 99.,  99.,   2.,   3.],
        [ 99.,  99., 777.,   7.],
        [  8.,   9.,  10.,  11.]])

# 2.1.3 Operations

In [73]:
X[2]

tensor([ 8.,  9., 10., 11.])

In [74]:
torch.exp(X[2])

tensor([ 2980.9580,  8103.0840, 22026.4648, 59874.1406])

In [77]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
#### rows (axis 0) snd columns refers (axis 1)

In [79]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [80]:
torch.cat((X, Y), dim=0),  torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [81]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [84]:
# Summing all the elements in the tensor yields a tensor with only one element.
X.sum() , Y.sum()

(tensor(66.), tensor(30.))

# 2.1.4 Broadcasting

In [87]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b
# Since a and b are 3 × 1 and 1 × 2 matrices their shapes do not match up.

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [88]:
a.shape, b.shape     

(torch.Size([3, 1]), torch.Size([1, 2]))

In [89]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [98]:
a = torch.tensor([8,8,8]).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a)
print(b)
print(a + b)

tensor([[8],
        [8],
        [8]])
tensor([[0, 1]])
tensor([[8, 9],
        [8, 9],
        [8, 9]])


# 2.1.5 Saving Memory

In [101]:
before = id(Y)
print(before)
Y = Y + X
print(id(Y) == before)
print(id(Y))

2777913563696
False
2777913564704


In [102]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2777913563696
id(Z): 2777913563696


In [103]:
before = id(X)
X += Y
id(X) == before

True

# 2.1.6 Conversion to Other Python Objects

In [105]:
 A = X.numpy()
 B = torch.from_numpy(A)
 type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [106]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)